################################################################################################################################################
#############################################              测试环境            ##################################################################
################################################################################################################################################

####################################
#        embedded tomcat配置       #
####################################
server:
  port: 8087
  servlet:
    ##session配置
    session:
      timeout: 86400 #设置为1天
    #设置session超时时间，默认30min,最短1min,设置 单位是秒

####################################
#             默认错误信息获取      #
####################################
  error:
#    默认报错信息中包含校验错误
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
    include-message: always

####################################
#           RabbitMQ 配置      #
####################################
spring:
  rabbitmq:
    host: "172.16.207.221"
    port: 5672
    username: "admin"
    password: "123"
    #设置rabbit-server端，交换机进行发送确认【CORRELATED：发布消息成功到交换器后会触发回调方法】
    publisher-confirm-type: correlated

####################################
#          logback日志配置          #
####################################
logging:
  config: classpath:logback-spring-dev.xml
#  level:


#
